# Generated by Django 5.2.1 on 2025-05-28 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("author", models.CharField(max_length=50, verbose_name="author")),
                (
                    "translator",
                    models.CharField(max_length=50, verbose_name="translator"),
                ),
                (
                    "publisher",
                    models.CharField(max_length=30, verbose_name="publisher"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="price"
                    ),
                ),
                ("body", models.TextField(default=None, verbose_name="body")),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("modified_datetime", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
