# Generated by Django 5.2.1 on 2025-06-08 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                ("body", models.TextField(verbose_name="توضیحات")),
                ("author", models.CharField(max_length=50, verbose_name="نویسنده")),
                (
                    "category",
                    models.CharField(
                        max_length=50, null=True, verbose_name="دسته بندی"
                    ),
                ),
                (
                    "page_num",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد صفحه"
                    ),
                ),
                (
                    "shabak_num",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10,13}$", "شابک باید ۱۰ یا ۱۳ رقمی باشد."
                            )
                        ],
                        verbose_name="شابک",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="ناشر"
                    ),
                ),
                (
                    "translator",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="مترجم"
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سال انتشار"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="covers/", verbose_name="جلد"
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="قیمت"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="فارسی", max_length=50, null=True, verbose_name="زبان"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("readed", "خوانده شده"),
                            ("borrowed", "قرض داده شده"),
                            ("not readed", "خوانده نشده"),
                        ],
                        default="readed",
                        max_length=30,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0.0, verbose_name="میانگین امتیاز"),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد نظرات"),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "modified_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب",
                "verbose_name_plural": "کتاب\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        verbose_name="امتیاز",
                    ),
                ),
                ("comment", models.TextField(verbose_name="نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="books.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="books_book_author_b941fe_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["shabak_num"], name="books_book_shabak__073a74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["book", "user"], name="books_revie_book_id_c4fa17_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("book", "user")},
        ),
    ]
