# Generated by Django 5.2.1 on 2025-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="title")),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="create_datetime",
            new_name="created_datetime",
        ),
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="book",
            name="page_num",
            field=models.PositiveIntegerField(null=True, verbose_name="page number"),
        ),
        migrations.AddField(
            model_name="book",
            name="shabak_num",
            field=models.CharField(
                max_length=20, null=True, unique=True, verbose_name="shabak number"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.DateField(
                blank=True, null=True, verbose_name="year of publish"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=30, verbose_name="author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="body",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(max_length=20, null=True, verbose_name="publisher"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=30, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="book",
            name="translator",
            field=models.CharField(max_length=30, null=True, verbose_name="translator"),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(
                related_name="categories", to="books.category"
            ),
        ),
    ]
