# Generated by Django 5.2.1 on 2025-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_remove_book_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="سال انتشار"
            ),
        ),
    ]
