# Generated by Django 5.2.1 on 2025-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(related_name="books", to="books.category"),
        ),
    ]
