# Generated by Django 5.2.1 on 2025-06-08 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
    ]
