# Generated by Django 5.2.1 on 2025-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(max_length=20, null=True, verbose_name="category"),
        ),
    ]
