# Generated by Django 5.2.1 on 2025-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_book_category_delete_category_book_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers"),
        ),
    ]
