# Generated by Django 5.2.1 on 2025-06-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_book_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="دسته بندی"),
        ),
    ]
