# Generated by Django 5.2.1 on 2025-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0005_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(max_length=50, null=True, verbose_name="category"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50, verbose_name="title"),
        ),
    ]
