# Generated by Django 5.2.1 on 2025-06-06 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_category_alter_book_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "کتاب", "verbose_name_plural": "کتاب\u200cها"},
        ),
        migrations.AddField(
            model_name="book",
            name="average_rating",
            field=models.FloatField(default=0.0, verbose_name="میانگین امتیاز"),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                default="فارسی", max_length=50, null=True, verbose_name="زبان"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="review_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد نظرات"),
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                null=True,
                unique=True,
                verbose_name="اسلاگ",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("readed", "خوانده شده"),
                    ("borrowed", "قرض داده شده"),
                    ("not readed", "خوانده نشده"),
                ],
                default="readed",
                max_length=30,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=50, verbose_name="نویسنده"),
        ),
        migrations.AlterField(
            model_name="book",
            name="body",
            field=models.TextField(verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(max_length=50, null=True, verbose_name="دسته بندی"),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/", verbose_name="جلد"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="book",
            name="modified_datetime",
            field=models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
        ),
        migrations.AlterField(
            model_name="book",
            name="page_num",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="تعداد صفحه"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="قیمت",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ناشر"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="shabak_num",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,13}$", "شابک باید ۱۰ یا ۱۳ رقمی باشد."
                    )
                ],
                verbose_name="شابک",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=50, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="book",
            name="translator",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="مترجم"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="books",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.DateField(blank=True, null=True, verbose_name="سال انتشار"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="books_book_author_b941fe_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["shabak_num"], name="books_book_shabak__073a74_idx"
            ),
        ),
    ]
