# Generated by Django 5.2.1 on 2025-06-10 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_alter_book_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publisher",
        ),
        migrations.RemoveField(
            model_name="book",
            name="translator",
        ),
    ]
