# Generated by Django 5.2.1 on 2025-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_remove_book_publisher_remove_book_translator"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(blank=True, max_length=50, verbose_name="ناشر"),
        ),
        migrations.AddField(
            model_name="book",
            name="translator",
            field=models.CharField(blank=True, max_length=50, verbose_name="مترجم"),
        ),
    ]
