# Generated by Django 5.2.1 on 2025-06-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="قیمت"
            ),
        ),
    ]
