# Generated by Django 5.2.1 on 2025-06-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0009_book_publisher_book_translator"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("w", "wating"), ("a", "approved"), ("na", "not approved")],
                default="a",
                max_length=3,
            ),
        ),
    ]
