# Generated by Django 5.2.1 on 2025-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0010_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[("w", "wating"), ("a", "approved"), ("na", "not approved")],
                default="a",
                max_length=3,
                verbose_name="وضعیت",
            ),
        ),
    ]
