# Generated by Django 5.2.1 on 2025-07-01 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0011_alter_review_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="book",
            name="review_count",
        ),
    ]
