# Generated by Django 5.2.1 on 2025-07-06 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0013_alter_book_shabak_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="shabak_num",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10,13}$", "شابک باید ۱۰ یا ۱۳ رقمی باشد."
                    )
                ],
                verbose_name="شابک",
            ),
        ),
    ]
